base_frame: 'base_link'
odom_frame: 'odom'
# In meters
wheel_diameter: 0.5078
# 4 times the pulses per rotation from the transducer
counts_per_rotation: 2000
# Axle track (positive if encoder is on the left wheel, negative if on right
track: 0.92
# Number of samples used for automatic drift correction (0 to disable)
drift_correction: 200